name: Main
on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */12 * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  # don't forget to change if you're using 'master' branch
  push:
    branches:
      - main
jobs:
  profile-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GPAT }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: github-profile-3d-contrib.json
      - name: push SVGs to the output-3d branch
        uses: crazy-max/ghaction-github-pages@lates
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GPAT }}
  default-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.base.svg
          token: ${{ secrets.GPAT }}
          base: header, activity, community, repositories, metadata
  most-used:
    runs-on: ubuntu-latest
    steps:
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: output/details.svg
          token: ${{ secrets.GPAT }}
          base: ""
          repositories_skipped: chatbot-ui, gitHub-readme-stats-clone, PL0-compiler
          plugin_languages: yes
          plugin_languages_ignored: >-
            tex, less, qmake, lex, gnuplot, javascript, html, css, ruby, applescript
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_followup: yes
          plugin_followup_indepth: yes
  compact-display:
    runs-on: ubuntu-latest
    steps:
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: output/metrics.plugin.achievements.compact.svg
          token: ${{ secrets.GPAT }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
